services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  mysql:
    image: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: superpassword
      MYSQL_DATABASE: salesorder
      MYSQL_USER: super
      MYSQL_PASSWORD: superpassword
    ports:
      - '3307:3306'
